version: '3'

services:
  app:
    container_name: libreria
    build:
      context: ./volumen
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "25:25"
    volumes:
      - ./volumen:/app

    
